// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6NzPO-qNu8SciTLzZrY4mJ8cWUPtsLpY',
    appId: '1:468981268029:web:ee9d8d80dec82c56a1b454',
    messagingSenderId: '468981268029',
    projectId: 'flutterfireb-8e256',
    authDomain: 'flutterfireb-8e256.firebaseapp.com',
    storageBucket: 'flutterfireb-8e256.firebasestorage.app',
    measurementId: 'G-QN1CYYF8QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhlUvpQhJtyFR-K2Ov_RdXXLhkb1V3UTo',
    appId: '1:468981268029:android:f5450fe77e4d4c74a1b454',
    messagingSenderId: '468981268029',
    projectId: 'flutterfireb-8e256',
    storageBucket: 'flutterfireb-8e256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA485K9HoVK0N-Gbj5ertRfILL81eg34Jc',
    appId: '1:468981268029:ios:f55c551b01a89e27a1b454',
    messagingSenderId: '468981268029',
    projectId: 'flutterfireb-8e256',
    storageBucket: 'flutterfireb-8e256.firebasestorage.app',
    iosBundleId: 'com.test.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA485K9HoVK0N-Gbj5ertRfILL81eg34Jc',
    appId: '1:468981268029:ios:f55c551b01a89e27a1b454',
    messagingSenderId: '468981268029',
    projectId: 'flutterfireb-8e256',
    storageBucket: 'flutterfireb-8e256.firebasestorage.app',
    iosBundleId: 'com.test.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6NzPO-qNu8SciTLzZrY4mJ8cWUPtsLpY',
    appId: '1:468981268029:web:c42ae0c29b4a6f64a1b454',
    messagingSenderId: '468981268029',
    projectId: 'flutterfireb-8e256',
    authDomain: 'flutterfireb-8e256.firebaseapp.com',
    storageBucket: 'flutterfireb-8e256.firebasestorage.app',
    measurementId: 'G-P2DP02GQ30',
  );
}
